apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app
  namespace: prod
  labels:
    app: color
    environment: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
      - image: tayebe/color-app:1.0.8
        name: white
        env:
        - name: "COLOR_BACKGROUND"
          value: "white"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
