apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app
  namespace: default
  labels:
    app: color
spec:
  replicas: 2
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
      - image: phantasm/color-app:1.0.1
        name: white
        env:
        - name: "COLOR_BACKGROUND"
          value: "white"
        ports:
        - containerPort: 8080
