apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app
  namespace: qa
  labels:
    app: color
    environment: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
      - name: white
        image: tayebe/color-app:1.0.8
        env:
        - name: "COLOR_BACKGROUND"
          value: "white"
        ports:
        - containerPort: 8080
