apiVersion: v1
kind: Namespace
metadata:
  name: color-app
  annotations:
    name: qa
  labels:
    aws-observability: enabled
    app: color

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app
  namespace: qa
  labels:
    app: color
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
        - image: tayebe/color-app:1.0.0
          name: white
          env:
          - name: "COLOR_BACKGROUND"
            value: "white"
          - name: "COLOR_PORT"
            value: "3000"
          ports:
          - containerPort: 3000
