apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: color-app-automation
  namespace: qa
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: k8s-fluxcd
  git:
    commit:
      author:
        email: "tayebekavousi68@gmail.com"
        name: "Flux Bot"
      messageTemplate: "Update image to {{.ImagePolicy.Name}}:{{.NewImage}}"
    push:
      branch: master
  update:
    path: ./clusters/cluster1/qa
    strategy: Setters
