---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qa
  namespace: flux-system
spec:
  interval: 1s
  path: ./clusters/cluster1/qa
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-fluxcd
